### ISSUE TITLE
warning: couldn't activate the cucumber_features plugin, skipping

### ISSUE THREAD

**Issue by hedgehog** [drnic/newgem#2]
1. I create a project using newgem (log is below)
2. run `rake features` and get the error:
   warning: couldn't activate the cucumber_features plugin, skipping

Google indicates "cucumber_features" is pretty specific to newgem :)
Appreciate any hits/tips.
# newgem log

```
  exists  
  create  lib
  create  script
  create  lib/ffi-hdf
  create  History.txt
  create  Rakefile
  create  README.rdoc
  create  PostInstall.txt
  create  lib/ffi-hdf.rb
```

  dependency  install_rspec
      create    spec
      create    tasks
      create    spec/ffi-hdf_spec.rb
      create    spec/spec.opts
      create    spec/spec_helper.rb
      create    tasks/rspec.rake
  dependency  install_website
      create    website/javascripts
      create    website/stylesheets
      create    config
      exists    script
      create    website/index.txt
      create    website/index.html
      create    config/website.yml.sample
      create    script/txt2html
  dependency    plain_theme
      exists      website/javascripts
      exists      website/stylesheets
      create      website/template.html.erb
      create      website/stylesheets/screen.css
      create      website/javascripts/rounded_corners_lite.inc.js
  dependency  install_cucumber
      create    features/step_definitions
      create    features/support
      create    features/development.feature
      create    features/step_definitions/common_steps.rb
      create    features/support/env.rb
      create    features/support/common.rb
      create    features/support/matchers.rb
  dependency  install_rubigen_scripts
      exists    script
      create    script/generate
      create    script/destroy
      create  script/console
      create  Manifest.txt
      readme  readme
# Important
- Open Rakefile
- Update missing details (gem description, dependent gems, etc.)

**Comment by hedgehog** [comment]
Moved to lighthouse ticketing system:

http://drnic.lighthouseapp.com/projects/18881-newgem/tickets/20-warning-couldnt-activate-the-cucumber_features-plugin-skipping

**Comment by drnic** [comment]
Is this still an issue? I think the hoe plugin is cucumberfeatures now

**Comment by hedgehog** [comment]
Works for me right now. Thanks
