### ISSUE TITLE
[Wishlist] RSpec+RCov Support

### ISSUE THREAD

**Issue by claco** [drnic/newgem#6]
First, I'm a total Ruby/Rails/RSpec/rCov Newb, so be kind. :-)

I've been using newgem to create a new project every time I start working on a new code kata in Ruby. While there's a nice option for rspec support, I find myself always trying to run rake rcov, which does nothing for spec tests, then fumbling on the net to find a rake task.

Here's the rake task I usually find and apply. If would be nice if this was either generated when the rspec options were used, or there was another option to do so.

```
begin
  require 'rcov'
rescue LoadError
  require 'rubygems' unless ENV['NO_RUBYGEMS']
  require 'rcov'
end

"Run all specs with rcov and store coverage report in doc/output/coverage"
Spec::Rake::SpecTask.new(:spec_rcov) do |t|
  t.spec_files = FileList['spec/**/*.rb']
  t.rcov = true
  t.rcov_dir = 'doc/output/coverage'
  t.rcov_opts = ['-t --exclude', 'spec,\.autotest,rcov.rb']
end
```

**Comment by drnic** [comment]
If you upgrade to hoe 2.3.3, it has rcov already built in. So all your projects should have a "rake rcov" task.

If you don't like their rcov task (http://github.com/seattlerb/hoe/blob/a05c7ab9610ae1c6dba27df7cded5f7689d5ab8c/lib/hoe/rcov.rb) perhaps fork hoe and extend the hoe plugin there for your tastes?
