### ISSUE TITLE
activesupport dependency

### ISSUE THREAD

**Issue by mdkent** [drnic/newgem#8]
In doing the package review for Fedora it was noted that activesupport is required but seemingly not referenced in the code. Though it does look like rubigen pulls it in.

Can the reference be removed?

**Comment by drnic** [comment]
Yep rubigen, like rails generators code originally, uses activesupport. I don't want to do the work to remove it as a reference, sorry :)

Why don't you want activesupport installed?

**Comment by mdkent** [comment]
No beef with activesupport - just looking for clarification on the dependency so my package is correct. Does newgem have a direct dependency on it I'm missing?
