### ISSUE TITLE
Can't require 'newgem' when ActiveSupport 3.0.0.beta is installed

### ISSUE THREAD

**Issue by gcampbell** [drnic/newgem#9]
`Gem::LoadError: can't activate activesupport (= 2.3.5, runtime) for ["rubigen-1.5.4", "newgem-1.5.2"], already activated activesupport-3.0.0.beta for ["newgem-1.5.2"]`

Rubigen has a hard dependency on 2.3.5, but newgem just depends on >= 2.0.2; when requiring newgem, RubyGems will pull in the most recent version of ActiveSupport, which will break if any versions > 2.3.5 are installed.

**Comment by drnic** [comment]
Oooh, I didn't release the fix for this; I have an uncommitted change that looks like I was trying to fix this already and got distracted. I'll test it and release.

**Comment by drnic** [comment]
Ok 1.5.3 is released. Let me know if it fixes/doesn't fix the problem.

I did a quick test and it seems ok with 3.0.0beta installed.

**Comment by gcampbell** [comment]
Works fine, thanks!
